# Generated by Django 5.1.15 on 2026-10-07 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Telefon OTP',
                'verbose_name_plural': 'Telefon OTP kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Familiya')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Rasm')),
                ('role', models.CharField(choices=[('USER', 'Foydalanuvchi'), ('DEALER', 'Diler / Avtosalon'), ('SERVICE_OWNER', 'Avtoservis egasi'), ('PARTS_SELLER', 'Ehtiyot qismlar sotuvchisi'), ('EMPLOYEE', 'Xodim'), ('ACCOUNTANT', 'Buxgalter / Kassa'), ('MANAGER', 'Menejer'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], db_index=True, default='USER', max_length=30, verbose_name='Rol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_type', models.CharField(choices=[('INDIVIDUAL', 'Jismoniy shaxs'), ('DEALER', 'Rasmiy diler'), ('STORE', "Do'kon / Magazin")], default='INDIVIDUAL', max_length=20)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Tasdiqlanmagan'), ('PENDING', 'Kutilmoqda'), ('VERIFIED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], db_index=True, default='UNVERIFIED', max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotuvchi profili',
                'verbose_name_plural': 'Sotuvchi profillari',
            },
        ),
    ]
