# Generated by Django 5.1.15 on 2026-10-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yoshi'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='Toshkent', max_length=100, verbose_name='Shahar / Viloyat'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=10, verbose_name='Jinsi'),
        ),
    ]
