# Generated by Django 5.1.15 on 2026-10-07 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name="E'lon sarlavhasi")),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING_MODERATION', 'Moderatsiyada'), ('ACTIVE', 'Faol / Sotuvda'), ('RESERVED', 'Band qilingan'), ('SOLD', 'Sotilgan'), ('REJECTED', 'Rad etilgan'), ('EXPIRED', 'Muddati tugagan'), ('BLOCKED', 'Bloklangan'), ('ARCHIVED', 'Arxivlangan')], db_index=True, default='PENDING_MODERATION', max_length=30)),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Tanlanganlar soni')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Tavsiya etilgan')),
                ('is_vip', models.BooleanField(db_index=True, default=False, verbose_name="VIP e'lon")),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rad etish sababi')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-is_vip', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPromotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package', models.CharField(choices=[('TOP', "Top o'rinda"), ('VIP', "VIP e'lon"), ('FEATURED', 'Tavsiya etilgan'), ('URGENT', 'Shoshilinch')], default='VIP', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='marketplace.listing')),
            ],
            options={
                'verbose_name': "E'lon reklamasi",
                'verbose_name_plural': "E'lon reklamalari",
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='vehicles/%Y/%m/', verbose_name='Rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartibi')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('ai_verified', models.BooleanField(default=False, verbose_name="AI tekshiruvidan o'tgan")),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AI ishonchlilik darajasi (%)')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.listing')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Avtomobil rasmi',
                'verbose_name_plural': 'Avtomobil rasmlari',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='marketplace.listing')),
            ],
            options={
                'verbose_name': "Saqlangan e'lon",
                'verbose_name_plural': "Saqlangan e'lonlar",
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
