# Generated by Django 5.1.15 on 2026-10-07 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('LISTING', "E'lon"), ('USER', 'Foydalanuvchi'), ('REVIEW', 'Sharh')], default='LISTING', max_length=20)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(choices=[('FAKE_LISTING', "Soxta e'lon"), ('WRONG_VEHICLE', "Noto'g'ri avtomobil modeli/ma'lumoti"), ('FAKE_PRICE', "Soxta yoki noto'g'ri narx"), ('FRAUD', 'Firibgarlik shubhasi'), ('DUPLICATE', "Dublikat / Takroriy e'lon"), ('OFFENSIVE', 'Haqoratomuz yoki nomaqbul kontent'), ('OTHER', 'Boshqa sabab')], default='FAKE_LISTING', max_length=30)),
                ('description', models.TextField(blank=True, verbose_name='Batafsil izoh')),
                ('status', models.CharField(choices=[('PENDING', "Ko'rib chiqilmoqda"), ('RESOLVED', 'Hal etildi'), ('DISMISSED', 'Rad etildi / Asossiz')], db_index=True, default='PENDING', max_length=20)),
                ('moderator_comment', models.TextField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shikoyat',
                'verbose_name_plural': 'Shikoyatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
