# Generated by Django 5.1.15 on 2026-10-07 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Marka nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Avtomobil markasi',
                'verbose_name_plural': 'Avtomobil markalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Avlod nomi')),
                ('year_from', models.PositiveIntegerField(verbose_name='Boshlangan yili')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name="Tugagan yili (hozirgacha bo'lsa bo'sh)")),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model avlodi',
                'verbose_name_plural': 'Model avlodlari',
                'ordering': ['-year_from'],
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.CharField(max_length=50, verbose_name='Dvigatel hajmi / kodi')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Benzin'), ('DIESEL', 'Dizel'), ('GAS_METHANE', 'Metan gaz'), ('GAS_PROPANE', 'Propan gaz'), ('ELECTRIC', 'Elektr'), ('HYBRID', 'Gibrid')], default='PETROL', max_length=20)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Mexanika'), ('AUTOMATIC', 'Avtomat'), ('ROBOT', 'Robot'), ('VARIATOR', 'Variator (CVT)')], default='AUTOMATIC', max_length=20)),
                ('drive_type', models.CharField(choices=[('FWD', 'Oldi uzatma (Old tortar)'), ('RWD', 'Orqa uzatma (Orqa tortar)'), ('AWD', "To'liq uzatma (Doimiy 4x4 / AWD)"), ('4WD', "Ulanuvchi to'liq uzatma (Part-time 4WD)")], default='FWD', max_length=20)),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ot kuchi (HP)')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='vehicles.generation')),
            ],
            options={
                'verbose_name': 'Modifikatsiya',
                'verbose_name_plural': 'Modifikatsiyalar',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Model nomi')),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('body_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hetchbek'), ('SUV', 'SUV / Yo‘ltanlamas'), ('CROSSOVER', 'Krossover'), ('COUPE', 'Kupe'), ('MINIVAN', 'Miniven'), ('PICKUP', 'Pikap'), ('WAGON', 'Universal'), ('CABRIOLET', 'Kabriolet')], default='SEDAN', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.brand', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Avtomobil modeli',
                'verbose_name_plural': 'Avtomobil modellari',
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Ishlab chiqarilgan yili')),
                ('mileage', models.PositiveIntegerField(db_index=True, verbose_name='Yurgan masofasi (km)')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('UZS', "UZS (So'm)")], default='USD', max_length=10)),
                ('color', models.CharField(max_length=50, verbose_name='Rangi')),
                ('body_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hetchbek'), ('SUV', 'SUV / Yo‘ltanlamas'), ('CROSSOVER', 'Krossover'), ('COUPE', 'Kupe'), ('MINIVAN', 'Miniven'), ('PICKUP', 'Pikap'), ('WAGON', 'Universal'), ('CABRIOLET', 'Kabriolet')], default='SEDAN', max_length=30)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Benzin'), ('DIESEL', 'Dizel'), ('GAS_METHANE', 'Metan gaz'), ('GAS_PROPANE', 'Propan gaz'), ('ELECTRIC', 'Elektr'), ('HYBRID', 'Gibrid')], default='PETROL', max_length=20)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Mexanika'), ('AUTOMATIC', 'Avtomat'), ('ROBOT', 'Robot'), ('VARIATOR', 'Variator (CVT)')], default='MANUAL', max_length=20)),
                ('engine', models.CharField(blank=True, max_length=50, verbose_name='Dvigatel')),
                ('drive_type', models.CharField(choices=[('FWD', 'Oldi uzatma (Old tortar)'), ('RWD', 'Orqa uzatma (Orqa tortar)'), ('AWD', "To'liq uzatma (Doimiy 4x4 / AWD)"), ('4WD', "Ulanuvchi to'liq uzatma (Part-time 4WD)")], default='FWD', max_length=20)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=17, verbose_name='VIN raqami')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Shahar')),
                ('region', models.CharField(db_index=True, max_length=100, verbose_name='Viloyat')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.brand')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.generation')),
                ('modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='vehicles.vehiclemodel'),
        ),
    ]
