# Generated by Django 5.1.15 on 2026-10-07 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Amal (Action)')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='Model nomi')),
                ('object_id', models.CharField(db_index=True, max_length=100, verbose_name='Obyekt ID')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name="Eski ma'lumot")),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name="Yangi ma'lumot")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzili')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit jurnali',
                'verbose_name_plural': 'Audit jurnallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
